version: '3.6'
services:

  redis:
    image: redis/redis-stack-server
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  trino:
    image: fieldengineering/redis-sql-trino:early-access
    hostname: trino
    container_name: trino
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDISEARCH_URI: 'redis://redis:6379'
      REDISEARCH_CASE_INSENSITIVE_NAMES: 'true'
