name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      branch:
        description: 'Branch'
        default: 'master'
        required: true

jobs:
  release:
    name: Release
    uses: redis-field-engineering/redis-github-workflows/.github/workflows/release-maven.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      publish: true
      java-version: 17
    secrets:
      github-token: ${{ secrets.GIT_ACCESS_TOKEN }}
      gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
      gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}
      sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
      sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

  docker:
    name: 'Docker'
    needs: [release]
    uses: redis-field-engineering/redis-github-workflows/.github/workflows/docker.yml@main
    with:
      tags: fieldengineering/redis-sql-trino:latest,fieldengineering/redis-sql-trino:${{ github.event.inputs.version }}
    secrets:
      github-token: ${{ secrets.GIT_ACCESS_TOKEN }}
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-password: ${{ secrets.DOCKER_PASSWORD }}